/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellClausesRouteImport } from './routes/_shell.clauses'
import { Route as ShellComplianceRouteImport } from './routes/_shell.compliance'
import { Route as ShellCredentialingRouteImport } from './routes/_shell.credentialing'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFeedRouteImport } from './routes/_shell.feed'
import { Route as ShellObligationsRouteImport } from './routes/_shell.obligations'
import { Route as ShellPipelineRouteImport } from './routes/_shell.pipeline'
import { Route as ShellRatesRouteImport } from './routes/_shell.rates'
import { Route as ShellRenewalsRouteImport } from './routes/_shell.renewals'
import { Route as ShellReviewRouteImport } from './routes/_shell.review'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellContractsIndexRouteImport } from './routes/_shell.contracts.index'
import { Route as ShellContractsDigitizeRouteImport } from './routes/_shell.contracts.digitize'
import { Route as ShellContractsNewgenRouteImport } from './routes/_shell.contracts.newgen'
import { Route as ShellContractsViewerIdRouteImport } from './routes/_shell.contracts.viewer.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellClausesRoute = ShellClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComplianceRoute = ShellComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCredentialingRoute = ShellCredentialingRouteImport.update({
  id: '/credentialing',
  path: '/credentialing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFeedRoute = ShellFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellObligationsRoute = ShellObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelineRoute = ShellPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRatesRoute = ShellRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRenewalsRoute = ShellRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewRoute = ShellReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsIndexRoute = ShellContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsDigitizeRoute = ShellContractsDigitizeRouteImport.update({
  id: '/contracts/digitize',
  path: '/contracts/digitize',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsNewgenRoute = ShellContractsNewgenRouteImport.update({
  id: '/contracts/newgen',
  path: '/contracts/newgen',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsViewerIdRoute = ShellContractsViewerIdRouteImport.update({
  id: '/contracts/viewer/$id',
  path: '/contracts/viewer/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clauses': typeof ShellClausesRoute
  '/compliance': typeof ShellComplianceRoute
  '/credentialing': typeof ShellCredentialingRoute
  '/dashboard': typeof ShellDashboardRoute
  '/feed': typeof ShellFeedRoute
  '/obligations': typeof ShellObligationsRoute
  '/pipeline': typeof ShellPipelineRoute
  '/rates': typeof ShellRatesRoute
  '/renewals': typeof ShellRenewalsRoute
  '/review': typeof ShellReviewRoute
  '/users': typeof ShellUsersRoute
  '/contracts/digitize': typeof ShellContractsDigitizeRoute
  '/contracts/newgen': typeof ShellContractsNewgenRoute
  '/contracts/': typeof ShellContractsIndexRoute
  '/contracts/viewer/$id': typeof ShellContractsViewerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clauses': typeof ShellClausesRoute
  '/compliance': typeof ShellComplianceRoute
  '/credentialing': typeof ShellCredentialingRoute
  '/dashboard': typeof ShellDashboardRoute
  '/feed': typeof ShellFeedRoute
  '/obligations': typeof ShellObligationsRoute
  '/pipeline': typeof ShellPipelineRoute
  '/rates': typeof ShellRatesRoute
  '/renewals': typeof ShellRenewalsRoute
  '/review': typeof ShellReviewRoute
  '/users': typeof ShellUsersRoute
  '/contracts/digitize': typeof ShellContractsDigitizeRoute
  '/contracts/newgen': typeof ShellContractsNewgenRoute
  '/contracts': typeof ShellContractsIndexRoute
  '/contracts/viewer/$id': typeof ShellContractsViewerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/clauses': typeof ShellClausesRoute
  '/_shell/compliance': typeof ShellComplianceRoute
  '/_shell/credentialing': typeof ShellCredentialingRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/feed': typeof ShellFeedRoute
  '/_shell/obligations': typeof ShellObligationsRoute
  '/_shell/pipeline': typeof ShellPipelineRoute
  '/_shell/rates': typeof ShellRatesRoute
  '/_shell/renewals': typeof ShellRenewalsRoute
  '/_shell/review': typeof ShellReviewRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/contracts/digitize': typeof ShellContractsDigitizeRoute
  '/_shell/contracts/newgen': typeof ShellContractsNewgenRoute
  '/_shell/contracts/': typeof ShellContractsIndexRoute
  '/_shell/contracts/viewer/$id': typeof ShellContractsViewerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clauses'
    | '/compliance'
    | '/credentialing'
    | '/dashboard'
    | '/feed'
    | '/obligations'
    | '/pipeline'
    | '/rates'
    | '/renewals'
    | '/review'
    | '/users'
    | '/contracts/digitize'
    | '/contracts/newgen'
    | '/contracts/'
    | '/contracts/viewer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clauses'
    | '/compliance'
    | '/credentialing'
    | '/dashboard'
    | '/feed'
    | '/obligations'
    | '/pipeline'
    | '/rates'
    | '/renewals'
    | '/review'
    | '/users'
    | '/contracts/digitize'
    | '/contracts/newgen'
    | '/contracts'
    | '/contracts/viewer/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/clauses'
    | '/_shell/compliance'
    | '/_shell/credentialing'
    | '/_shell/dashboard'
    | '/_shell/feed'
    | '/_shell/obligations'
    | '/_shell/pipeline'
    | '/_shell/rates'
    | '/_shell/renewals'
    | '/_shell/review'
    | '/_shell/users'
    | '/_shell/contracts/digitize'
    | '/_shell/contracts/newgen'
    | '/_shell/contracts/'
    | '/_shell/contracts/viewer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/clauses': {
      id: '/_shell/clauses'
      path: '/clauses'
      fullPath: '/clauses'
      preLoaderRoute: typeof ShellClausesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/compliance': {
      id: '/_shell/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ShellComplianceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/credentialing': {
      id: '/_shell/credentialing'
      path: '/credentialing'
      fullPath: '/credentialing'
      preLoaderRoute: typeof ShellCredentialingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/feed': {
      id: '/_shell/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ShellFeedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/obligations': {
      id: '/_shell/obligations'
      path: '/obligations'
      fullPath: '/obligations'
      preLoaderRoute: typeof ShellObligationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipeline': {
      id: '/_shell/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof ShellPipelineRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rates': {
      id: '/_shell/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof ShellRatesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/renewals': {
      id: '/_shell/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof ShellRenewalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/review': {
      id: '/_shell/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ShellReviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts/': {
      id: '/_shell/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ShellContractsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts/digitize': {
      id: '/_shell/contracts/digitize'
      path: '/contracts/digitize'
      fullPath: '/contracts/digitize'
      preLoaderRoute: typeof ShellContractsDigitizeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts/newgen': {
      id: '/_shell/contracts/newgen'
      path: '/contracts/newgen'
      fullPath: '/contracts/newgen'
      preLoaderRoute: typeof ShellContractsNewgenRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts/viewer/$id': {
      id: '/_shell/contracts/viewer/$id'
      path: '/contracts/viewer/$id'
      fullPath: '/contracts/viewer/$id'
      preLoaderRoute: typeof ShellContractsViewerIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellClausesRoute: typeof ShellClausesRoute
  ShellComplianceRoute: typeof ShellComplianceRoute
  ShellCredentialingRoute: typeof ShellCredentialingRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFeedRoute: typeof ShellFeedRoute
  ShellObligationsRoute: typeof ShellObligationsRoute
  ShellPipelineRoute: typeof ShellPipelineRoute
  ShellRatesRoute: typeof ShellRatesRoute
  ShellRenewalsRoute: typeof ShellRenewalsRoute
  ShellReviewRoute: typeof ShellReviewRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellContractsDigitizeRoute: typeof ShellContractsDigitizeRoute
  ShellContractsNewgenRoute: typeof ShellContractsNewgenRoute
  ShellContractsIndexRoute: typeof ShellContractsIndexRoute
  ShellContractsViewerIdRoute: typeof ShellContractsViewerIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellClausesRoute: ShellClausesRoute,
  ShellComplianceRoute: ShellComplianceRoute,
  ShellCredentialingRoute: ShellCredentialingRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFeedRoute: ShellFeedRoute,
  ShellObligationsRoute: ShellObligationsRoute,
  ShellPipelineRoute: ShellPipelineRoute,
  ShellRatesRoute: ShellRatesRoute,
  ShellRenewalsRoute: ShellRenewalsRoute,
  ShellReviewRoute: ShellReviewRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellContractsDigitizeRoute: ShellContractsDigitizeRoute,
  ShellContractsNewgenRoute: ShellContractsNewgenRoute,
  ShellContractsIndexRoute: ShellContractsIndexRoute,
  ShellContractsViewerIdRoute: ShellContractsViewerIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
